# Control Tower config (example)
timezone: Europe/London
daily_digest_time: "08:00"
hmac:
  secret_env: CT_WEBHOOK_SECRET
rbac:
  roles:
    owner: ["*"]
    maintainer: ["events.read","runs.read","systems.read","triggers.exec"]
    operator: ["events.read","runs.read","systems.read","triggers.exec"]
    viewer: ["events.read","runs.read","systems.read"]
rate_limits:
  default_per_min: 60
  burst: 120
storage:
  retention_days:
    events: 180
    runs: 365
    systems: 90
