name: Phase Issue Guardian

on:
  issues:
    types: [opened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link check (lychee)
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose --max-concurrency 4 --accept 200,206,429 -- github-issue://${{ github.repository }}#${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Basic body heuristics
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            const mustContain = [
              "## Objectives",
              "## Dependencies",
              "## Entry Criteria",
              "## Exit Criteria",
              "## Risks & Mitigations",
              "## KPIs / Success Measures",
              "## Tasks",
              "## Approvals"
            ];
            const missing = mustContain.filter(h => !body.includes(h));
            if (missing.length) {
              core.setFailed(`Phase issue missing sections: ${missing.join(", ")}`);
            }
